package collectionsObjects;

public enum CollectionObjects {
	Set,
	SortedSet,
	NavigableSet,
	Queue,
	BlockingQueue,
	TransferQueue,
	Deque,
	BlockingDeque,
	SortedMap,
	NavigableMap,
	ConcurrentMap,
	ConcurrentNavigableMap,
	AbstractCollection, 
	AbstractList, 
	AbstractQueue, 
	AbstractSequentialList, 
	AbstractSet, 
	ArrayBlockingQueue,
	ArrayDeque, ArrayList,
	AttributeList,
	BeanContextServicesSupport, 
	BeanContextSupport, 
	ConcurrentLinkedDeque, 
	ConcurrentLinkedQueue, 
	ConcurrentSkipListSet,
	CopyOnWriteArrayList, 
	CopyOnWriteArraySet,
	DelayQueue,
	EnumSet,
	HashSet,
	JobStateReasons,
	LinkedBlockingDeque, 
	LinkedBlockingQueue, 
	LinkedHashSet,
	LinkedList, 
	LinkedTransferQueue, 
	PriorityBlockingQueue, 
	PriorityQueue, 
	RoleList,
	RoleUnresolvedList,
	Stack,
	SynchronousQueue, 
	TreeSet, 
	Vector
}
